kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: dev
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.nodejs.ua
    http:
      paths:
        - path: /dev
          backend:
            serviceName: nodejs-dev
            servicePort: 80