kind: Service
apiVersion: v1
metadata:
  name: nodejs-dev
  namespace: dev
  labels:
    app: nodejs-dev
spec:
  type: ClusterIP
  selector:
    app: nodejs-dev
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: nodejs-stage
  namespace: dev
  labels:
    app: nodejs-stage
spec:
  type: ClusterIP
  selector:
    app: nodejs-stage
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080